### PR TITLE
Update for Flarum beta 8

### PR DESCRIPTION
**Pull request by dsevillamartin**
**Changes made:**
- Updated `bootstrap.php` to utilize Extender
  - Renamed to `extend.php`
- Removed unnecessary Listeners
- Updated icon for FontAwesome 5
- Fixed composer.json schema

**Screenshots:**

image

### CODE REVIEW

**Comment by JoshyPHP** [comment]
Thanks for the heads-up but I'm going to hold off for the next public release and update all of my extensions at once. It should happen shortly after the next version is officially released.

**Comment by luceos** [comment]
@JoshyPHP Out of curiosity could you explain the reason for closing this PR? Wouldn't it help you later to merge this and move from there? David spend valuable time preparing this PR, just don't want it to go to waste.. 👍

**Comment by JoshyPHP** [comment]
1. I can't test it on my installation.
2. The whitespace doesn't match the style of the extension so I'd have to edit it.
3. I have to replicate the changes to the other extensions so I'd rather copy/paste the same code.

Whatever time was spent on this PR isn't necessarily wasted as I'll come back to this PR later to check out which parts of the API change between 0.1.0-beta7.1 and 0.1.0-beta8.

**Comment by JoshyPHP** [comment]
On that note, I should mention that anybody is welcome to create and maintain replacements for my extensions. Each of them is effectively 1 line of code to enable the relevant plugin (plus some boilerplate code) and I don't have plans on adding more features.

@datitisev If you want to create a replacement under your own namespace (iow not under `s9e`) please go ahead. If you tag me I'll subscribe to the relevant threads/repositories.

**Comment by luceos** [comment]
See https://github.com/FriendsOfFlarum/formatting

**Pull request closed without merging**
